language: node_js
install: npm install
env:
  - db_connection="mongodb+srv://Blaise:Blaise1...@cluster0.zxf6j.mongodb.net/portfolio?retryWrites=true&w=majority"
node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: true
script:
  - npm run test
after_success:
  - npm run coveralls